# Generated by Django 4.2.20 on 2025-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
